version: '3'
services:
  strapi:
    image: strapi/strapi
    volumes:
      - ./strapi:/srv/app
    ports:
      - '1340:1337'
    restart: unless-stopped
  front:
    build: front/
    ports:
      - 3001:3000
    volumes:
      - ./front:/usr/src/app
      - /usr/src/app/node_modules/
      - /usr/src/app/.next/
    environment:
      - STRAPI_HOST=strapi
    #restart: unless-stopped