version: '3'
services:
  strapi:
    build: strapi/
    volumes:
      - ./strapi:/usr/app
      - /usr/app/node_modules
      - /usr/app/build
    ports:
      - '1340:1340'
    restart: unless-stopped
  front:
    build:
      context: ./front
      dockerfile: Dockerfile.prod
    ports:
      - 3001:3000
    volumes:
      - ./front:/usr/src/app
      - /usr/src/app/node_modules/
      - /usr/src/app/.next/
    environment:
      - STRAPI_HOST=strapi
    depends_on: 
      - strapi