FROM node:12

ENV PORT 3000

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Installing dependencies
COPY package.json .
RUN yarn

COPY . /usr/src/app

EXPOSE 3000

# Running the app
CMD bash -c "yarn build && yarn start"
